{
  "_from": "async-err@0.0.2",
  "_id": "async-err@0.0.2",
  "_inBundle": false,
  "_integrity": "sha1-JUa8q7CVSg+GaO/GS6jLybEM2/s=",
  "_location": "/async-err",
  "_phantomChildren": {},
  "_requested": {
    "type": "version",
    "registry": true,
    "raw": "async-err@0.0.2",
    "name": "async-err",
    "escapedName": "async-err",
    "rawSpec": "0.0.2",
    "saveSpec": null,
    "fetchSpec": "0.0.2"
  },
  "_requiredBy": [
    "/npmview"
  ],
  "_resolved": "https://registry.npmjs.org/async-err/-/async-err-0.0.2.tgz",
  "_shasum": "2546bcabb0954a0f8668efc64ba8cbc9b10cdbfb",
  "_spec": "async-err@0.0.2",
  "_where": "C:\\Users\\johny\\Code\\github\\johnyherangi\\check-package-version\\node_modules\\npmview",
  "author": {
    "name": "Edmond Meinfelder"
  },
  "bugs": {
    "url": "https://github.com/stdarg/async-err/issues"
  },
  "bundleDependencies": false,
  "dependencies": {
    "debug": "0.7.4",
    "is2": "0.0.12"
  },
  "deprecated": false,
  "description": "An easy way to make an error in Node.js async, when it would sync otherwise.",
  "devDependencies": {
    "async": "0.2.10",
    "mocha": "1.17.1"
  },
  "homepage": "https://github.com/stdarg/async-err#readme",
  "keywords": [
    "error",
    "err",
    "async"
  ],
  "license": "MIT",
  "main": "index.js",
  "name": "async-err",
  "repository": {
    "type": "git",
    "url": "git://github.com/stdarg/async-err.git"
  },
  "scripts": {
    "test": "mocha --reporter list"
  },
  "version": "0.0.2"
}
